export const WORKOUT_LIST_REQUEST = "WORKOUT_LIST_REQUEST";
export const WORKOUT_LIST_SUCCESS = "WORKOUT_LIST_SUCCESS";
export const WORKOUT_LIST_FAIL = "WORKOUT_LIST_FAIL";

export const WORKOUT_DETAIL_REQUEST = "WORKOUT_DETAIL_REQUEST";
export const WORKOUT_DETAIL_SUCCESS = "WORKOUT_DETAIL_SUCCESS";
export const WORKOUT_DETAIL_FAIL = "WORKOUT_DETAIL_FAIL";
